homeassistant:
  name: Bungalow
  latitude: 37.800617
  longitude: -122.421918
  elevation: 0
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

# Enables support for tracking state changes over time
#history:

#enables detailed logging
logger:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#allows python scripts to be used
python_script:

discovery:
  ignore:
    - harmony
    - netgear_router
    - philips_hue

#entities
hue:
  bridges:
    - host: !secret hue_IP
      allow_unreachable: true
      allow_hue_groups: true

wemo:
  discovery: false
  static:
    - 192.168.1.8
    - 192.168.1.32
    - 192.168.1.36

#telegram text bot
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_api_key
#    allowed_chat_ids:
#      - !secret telegram_chat_ID

#harmony
remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony_IP

ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password

nest:
  client_id: !secret nest_client_ID
  client_secret: !secret nest_client_secret
  structure:
    - Bungalow

system_health:

wake_on_lan:

input_boolean:
  home:
    name: Is anyone home?
    initial: on
  cleaning_needed:
    name: Does roombalina need to run?
    initial: off
  alarm_on:
    initial: off
  in_bed:
    name: Is anyone in bed?
    initial: off
  living_room_motion:
    name: Living Room Motion Lights Status
    initial: on

input_datetime:
  wake_up_time:
    name: Morning Alarm Time
    has_date: false
    has_time: true
    initial: '08:00:00'
  bed_time:
    name: Bed Cooldown Time
    has_date: false
    has_time: true
    initial: '21:00:00'

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key
      host: !secret xiaomi_aqara_IP

device_tracker:
  - platform: netgear
    password: !secret netgear_password
    host: !secret netgear_IP
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes

zone:
  - name: Home
    latitude: 37.800667
    longitude: -122.4219
    radius: 50

group:
  default_view:
    view: true
    icon: mdi:home
    entities:
      - group.harry
      - group.sage
      - group.all_switches
      - input_datetime.wake_up_time
      - input_datetime.bed_time
      - input_boolean.alarm_on
      - input_boolean.cleaning_needed
      - input_boolean.home
      - input_boolean.in_bed
      - input_boolean.living_room_motion
      - sensor.humidity_bathroom
      - sensor.humidity_bedroom
      - sensor.temperature_bathroom
      - sensor.temperature_bedroom
  harry:
    view: false
    name: Harry Home Tracker
    entities:
      - device_tracker.harry_phone
  sage:
    view: false
    name: Sage Home Tracker
    entities:
      - device_tracker.sage_phone
  media:
    view: true
    name: Media Players
    entities:
      - group.tvs
      - group.audio
      - remote.harmony_hub
  tvs:
    view: false
    name: TV's
    entities:
      - media_player.bedroom_tv
      - media_player.living_room_tv
  audio:
    view: false
    name: Audio Players
    entities:
      - media_player.bathroom_speaker
      - media_player.bedroom_speaker
      - media_player.kitchen_speaker
      - media_player.surround
      - media_player.whole_house


automation: !include automations.yaml
